baseURL: https://blog.xn--7ovq92diups1e.com/
languageCode: zh-cn
title: 華鳥風月
theme: PaperModX
timeZone: Asia/Shanghai
hasCJKLanguage: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
pluralizeListTitles: false
paginate: 10

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Search
          url: search/
          weight: 1
        - name: Tags
          url: tags/
          weight: 9
        - name: Projects
          url: projects/
          weight: 10
        - name: About
          url: https://github.com/RyoLee
          weight: 99

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Ryo 的个人博客."
  author: Ryo
  # author: ["Me", "You"] # multiple authors
  defaultTheme: auto
  disableThemeToggle: false
  DateFormat: "2006-01-02"
  ShowFullTextinRSS: true

  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false # 隐藏页脚
  ShowWordCount: true
  ShowLastMod: true #显示文章更新时间
  disableSpecialistPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  TocSide: "left"
  #EnableInstantClick: true
  tocopen: true
  assets:
    disableFingerprinting: true

  editPost:
    URL: "https://github.com/RyoLee/blog/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true

  # home-info mode
  homeInfoParams:
    Title: "杂物箱"
    Content: Welcome

  utteranc:
    repo: "RyoLee/blog-comment"
    issueTerm: "pathname"
    theme: "github-light"

  socialIcons:
    - name: github
      url: "https://github.com/RyoLee"
    - name: twitter
      url: "https://twitter.com/Ryo_LV01"
    - name: RSS
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  minifyOutput: false

# markup:
#   goldmark:
#     renderer:
#       unsafe: true
#   highlight:
#     codeFences: true
#     guessSyntax: true
#     lineNos: true
#     # noClasses: false
#     style: github-gist

enableGitInfo: true
frontmatter:
  expiryDate: ["expiryDate"]
  date: ["date", "publishDate", "lastmod", ":git"]
  lastmod: [":git", "lastmod", ":fileModTime", ":default"]
  publishDate: ["publishDate", "date", ":git"]

taxonomies:
  tag: tags
  project: projects

outputs:
  home:
    - HTML
    - RSS
    - JSON
