name: Build

# 在 master 分支更新时触发构建
on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.97.3"
          extended: true

      - name: Build
        run: hugo --gc --minify --cleanDestinationDir

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          full_commit_message: Deploy from ${{ github.repository }}@${{ github.sha }}
